FROM amd64/alpine:latest

LABEL name='SSEChat'
LABEL version='1.0'
LABEL description="Ephemeral Chat on SSE"
LABEL org.ctrlaltdev.vendor='ctrlaltdev'


ARG PORT=1337

RUN set -x && apk --no-cache add python3 supervisor nodejs npm

RUN mkdir /opt/chat
COPY ./ /opt/chat
WORKDIR /opt/chat
RUN npm ci
RUN npm run build

EXPOSE 1337

ENTRYPOINT [ "/opt/chat/entrypoint.sh" ]
